[formatting]
    column_width = 100

    indent_entries = true
    indent_string = "    "
    indent_tables = true

    allowed_blank_lines = 3
    reoder_inline_tables = true
    reorder_arrays = true
    reorder_keys = true
